services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: porto_app
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001

  certbot:
    image: certbot/certbot:latest
    container_name: porto_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot